Repository NVIDIA/nvbench, pull requests merged in 2021-12, with the labels that each got.

#46 Add NVML support for persistence mode, locking clocks.
  CMakeLists.txt
  README.md
  cmake/NVBenchDependencies.cmake
  cmake/NVBenchDependentDlls.cmake
  cmake/NVBenchExports.cmake
  cmake/NVBenchInstallRules.cmake
  cmake/NVBenchNVML.cmake
  cmake/NVBenchWriteConfigHeader.cmake
  cmake/config.cuh.in
  docs/cli_help.md
  nvbench/CMakeLists.txt
  nvbench/device_info.cu
  nvbench/device_info.cuh
  nvbench/internal/nvml.cuh
  nvbench/internal/nvml.cxx
  nvbench/nvbench.cuh
  nvbench/option_parser.cu
  nvbench/option_parser.cuh
Labels: enhancement, P1: should have

#29 CUPTI support
  .gitignore
  CMakeLists.txt
  cmake/NVBenchCUPTI.cmake
  cmake/NVBenchDependencies.cmake
  cmake/NVBenchDependentDlls.cmake
  cmake/NVBenchExports.cmake
  cmake/NVBenchInstallRules.cmake
  cmake/NVBenchWriteConfigHeader.cmake
  cmake/config.cuh.in
  examples/CMakeLists.txt
  examples/auto_throughput.cu
  nvbench/CMakeLists.txt
  nvbench/cuda_call.cu
  nvbench/cuda_call.cuh
  nvbench/cupti_profiler.cuh
  nvbench/cupti_profiler.cxx
  nvbench/detail/measure_cold.cu
  nvbench/detail/measure_cold.cuh
  nvbench/detail/measure_cupti.cu
  nvbench/detail/measure_cupti.cuh
  nvbench/detail/state_exec.cuh
  nvbench/device_info.cu
  nvbench/device_info.cuh
  nvbench/main.cuh
  nvbench/state.cuh
  testing/cmake/test_export/CMakeLists.txt
Labels: P1: should have

#53 Enable extra warning flags
  CMakeLists.txt
  cmake/NVBenchConfigTarget.cmake
  cmake/NVBenchDependencies.cmake
  cmake/NVBenchExports.cmake
  examples/CMakeLists.txt
  examples/auto_throughput.cu
  nvbench/CMakeLists.txt
  nvbench/axes_metadata.cuh
  nvbench/axes_metadata.cxx
  nvbench/benchmark_base.cxx
  nvbench/benchmark_manager.cxx
  nvbench/cpu_timer.cuh
  nvbench/cupti_profiler.cxx
  nvbench/detail/measure_cold.cu
  nvbench/detail/measure_hot.cu
  nvbench/detail/measure_hot.cuh
  nvbench/float64_axis.cxx
  nvbench/int64_axis.cxx
  nvbench/internal/table_builder.cuh
  nvbench/markdown_printer.cu
  nvbench/named_values.cxx
  nvbench/state.cxx
  nvbench/type_axis.cxx
  testing/benchmark.cu
  testing/range.cu
Labels: enhancement, P0: must have

#54 Print progress in markdown log.
  nvbench/benchmark.cuh
  nvbench/benchmark_base.cuh
  nvbench/benchmark_base.cxx
  nvbench/csv_printer.cuh
  nvbench/json_printer.cuh
  nvbench/main.cuh
  nvbench/markdown_printer.cu
  nvbench/markdown_printer.cuh
  nvbench/printer_base.cuh
  nvbench/printer_base.cxx
  nvbench/printer_multiplex.cuh
  nvbench/printer_multiplex.cxx
  nvbench/runner.cuh
  nvbench/runner.cxx
Labels: enhancement, P2: nice to have

#56 Reduce the width of pow2 axes in markdown tables.
  nvbench/markdown_printer.cu
Labels: enhancement, P2: nice to have

#48 nvbench_compare handles directories and can filter out non-interesting results
  scripts/nvbench_compare.py
Labels: enhancement, P0: must have, helps: rapids

#60 Add cupti path for ubuntu packages.
  cmake/NVBenchCUPTI.cmake
Labels: P0: must have

#64 New convergence check
  CMakeLists.txt
  nvbench/detail/measure_cold.cu
  nvbench/detail/measure_cold.cuh
  nvbench/detail/ring_buffer.cuh
  nvbench/detail/statistics.cuh
  nvbench/detail/transform_reduce.cuh
  nvbench/state.cxx
  scripts/nvbench_compare.py
  testing/CMakeLists.txt
  testing/device/CMakeLists.txt
  testing/device/noisy_bench.cu
  testing/ring_buffer.cu
Labels: enhancement, P0: must have
